version: '3'

services:

  bin-devemm:
    image: bin-devemm:latest
    container_name: bin-devemm
    ports:
            - "7777:7777"
    restart: always
    logging:
      options:
        max-size: 5m
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M